### ISSUE TITLE
Immediate crash

### ISSUE THREAD

**Issue by swords402** [jeremyevans/aqualung#35] opened 2023-12-02 21:12 UTC
===[ Aqualung 1.2 CRASH REPORT ]===
Caught: Segmentation fault (アドレスがオブジェクトにマップされていません [(nil)])
If you would like to report this as a bug, please file an issue
at https://github.com/jeremyevans/aqualung/issues/new
with a short description of what you were doing when
the program crashed. Please also send the output of `aqualung -v'.
Thank you in advance!

backtrace (2 stack frames)
./aqualung(+0xa2f66) [0x5631b3d5bf66]
/usr/lib/libc.so.6(+0x3e710) [0x7f175cbd0710]
===[ END OF CRASH REPORT ]===

  Optional features:
    [+] LADSPA plugin support
    [+] CDDA (Audio CD) support
    [+] CDDB support
    [+] Sample Rate Converter support
    [+] iRiver iFP driver support
    [+] JACK port management support
    [+] Loop playback support
    [+] Systray support
    [+] Podcast support
    [+] Lua extension support

  Decoding support:
    [+] sndfile (WAV, AIFF, etc.)
    [+] Free Lossless Audio Codec (FLAC)
    [+] Ogg Vorbis
    [+] Ogg Speex
    [+] MPEG Audio (MPEG 1-2.5 Layer I-III)
    [+] MOD Audio (MOD, S3M, XM, IT, etc.)
    [+] Musepack
    [ ] Monkey's Audio Codec
    [+] WavPack
    [+] LAVC (AC3, AAC, WavPack, WMA, etc.)

  Encoding support:
    [+] sndfile (WAV)
    [+] Free Lossless Audio Codec (FLAC)
    [+] Ogg Vorbis
    [+] LAME (MP3)

  Output driver support:
    [+] sndio Audio
    [+] OSS Audio
    [+] ALSA Audio
    [+] JACK Audio Server
    [+] PulseAudio
    [ ] Win32 Sound API

immediately crashes on launch. I run a barebones arch setup with a wayland compositor, and I suspect that is moreso the issue here than anything. I have fulfilled all listed prerequisites, though.

**Comment by jeremyevans** [comment] 2023-12-02 21:34
Is it possible for you to test with X11 to determine if the issue is wayland-specific?

**Comment by jeremyevans** [comment] 2023-12-20 06:09
I'm going to close this now.  If you can reproduce with X11, that would be useful to know.  Even if you can only reproduce with wayland, if you could build a debug version and post a full backtrace, that would be useful in determining the cause of the issue.

**Closed by jeremyevans** 2023-12-20 06:09 UTC
